# 넘파이

**선형대수와 통계 등에 기반**  
**Numerical Python을 의미**  
**루프를 사용하지 않고 대량의 배열 연산 가능**  
**저수준 언어 기반의 호환 API를 제공**  
왜냐하면 넘파이는 빠른 배열 연산을 보장해주지만, 파이썬 언어 자체가 가지는 수행 성능의 제약이 있어서 수해 성능이 매우 중요한 부분은 C/C++ 기반의 코드로 작성하고 이를 넘파이에서 호출하는 방식으로 쉽게 통합이 가능하기 때문



In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type ', type(array1))
print('array1 형태 : ', array1.shape)

array2 = np.array([[1,2,3], [4,5,6]])
print('array2 type ', type(array2))
print('array2 shape : ', array2.shape)

array1 type  <class 'numpy.ndarray'>
array1 형태 :  (3,)
array2 type  <class 'numpy.ndarray'>
array2 shape :  (2, 3)


In [3]:
print('array1 : {:0}차원, array2 : {:1}차원 '.format(array1.ndim, array2.ndim))

array1 : 1차원, array2 : 2차원 


In [4]:
print(array1.dtype)

int32


더 큰 데이터 타입으로 형변환이 된다.

In [5]:
array2 = np.array([1, 2, 'test'])
array3 = np.array([1, 2, 3.0])

print(array2.dtype)
print(array3.dtype)

<U11
float64


astype으로 형변환이 가능하다.

메모리를 더 절약해야 할 때 이용한다. float64, float32, int64, int32 등이 있으므로!

In [6]:
array1 = np.array([1,2,3])
print(array1)
array1_float = array1.astype('float64')
print(array1_float)
array1_int = array1_float.astype('int32')
print(array1_int)
array_float2 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float2.astype('int32')
print(array_int2)

[1 2 3]
[1. 2. 3.]
[1 2 3]
[1 2 3]


쉽게 생성하기

In [7]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
array = np.arange(5, 10)
print(array)

[5 6 7 8 9]


In [9]:
zero_array = np.zeros((3, 2), dtype='int32')
one_array = np.ones((3, 2))
print(zero_array)
print(one_array)

[[0 0]
 [0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


reshape로 모양 변경하기

In [10]:
array = np.arange(10)
array1 = array.reshape(2, 5)
array2 = array.reshape(5, 2)
print(array)
print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1 = array.reshape(-1, 5)
array2 = array.reshape(5, -1)
print(array1, array1.shape)
print(array2, array2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


(-1, 1)과 같은 형태를 사용하면 3d를 2d로 1d를 2d로 바꿔줄 수 있다

In [12]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print(array3d, array3d.shape)
array2d = array3d.reshape(-1, 1)
print(array2d, array2d.shape)

#1차원을 2차원으로
array2d_2 = array1.reshape(-1, 1)
print(array2d_2, array2d_2.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


**인덱싱**

In [13]:
#단일 인덱싱
array1 = np.arange(1, 10)
print(array1[2])

# 2차원 배열로 변환
array2 = array1.reshape(3, -1)
print(array2)
print(array2[0, 1])
print(array2[1, 2])

3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
6


**axis = 1과 0이 중요하다**

axis = 0은 로우 방향의 축을 의미한다.  
axis = 1은 컬럼 방향의 축을 의미한다. 

여기서 중요한 것! **방향의** 라는 단어이다. 로우 방향은 아래로 가는 것이고, 컬럼 방향은 가로로 가는 것.

3차원이면 axis 0, 1, 2를 가지게 된다. 행, 열, 높이 이다.

In [14]:
#슬라이싱   -> 인덱싱 기반 접근이라 마지막 숫자 -1 까지의 값을 뽑아낸다.
print(array1[1:3])
print(array1[:5])
print(array1[4:])

[2 3]
[1 2 3 4 5]
[5 6 7 8 9]


In [15]:
print(array2[0:2, 0:2], '\n')
print(array2[1:3, 0:3], '\n')
print(array2[:2, 1:], '\n')

[[1 2]
 [4 5]] 

[[4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]] 



**불린 인덱싱**

조건 필터링과 검색을 동시에 할 수 있다.

5보다 큰 데이터를 추출하거나 그렇게 할 수 있는 것

In [16]:
array1d = np.arange(1, 10)
array_tmp = array1d[array1d > 5]

In [17]:
array_tmp

array([6, 7, 8, 9])

In [20]:
#단순히 아래와 같이 하면 True, False list가 나온다.
list = array1d > 5
list

array([False, False, False, False, False,  True,  True,  True,  True])

In [21]:
# 이것을 리스트에 적용하면 똑같이 뽑아낼 수 있다.
array_tmp = array1d[list]
array_tmp

array([6, 7, 8, 9])

# 정렬 sort()와 argsort()

numpy에서 행렬을 정렬하는 대표적인 방법인 np.sort()와 ndarray.sort() 그리고 정렬된 행렬의 인덱스를 반환하는 argsort()가 있다.

np.sort는 원본은 유지한 채 정렬된 행렬을 반환한다.  
ndarray.sort()는 원 행렬 자체를 정렬하고 반환은 없다.

In [22]:
original_array = np.array([5,1,3,9])
np_sort = np.sort(original_array)
np_sort

array([1, 3, 5, 9])

In [25]:
ndarray_sort = original_array.sort()
ndarray_sort

In [27]:
original_array.sort()
original_array

array([1, 3, 5, 9])

**내림차순 정렬**

In [28]:
original_array = np.array([5,1,3,9])
np_sort = np.sort(original_array)[::-1]
np_sort

array([9, 5, 3, 1])

In [31]:
original_array.sort()
original_array[::-1]

array([9, 5, 3, 1])

2차원 이상일 경우에는 axis를 이용해서 정렬할 수 있다.

0은 행 방향, 1은 열 방향이다.



In [37]:
array = np.array([[4, 25],
                 [55,15]])
array

array([[ 4, 25],
       [55, 15]])

In [38]:
# 행 방향으로 정렬
array_sort = np.sort(array, axis = 0)
array_sort

array([[ 4, 15],
       [55, 25]])

In [39]:
array_sort = np.sort(array, axis = 1)
array_sort

array([[ 4, 25],
       [15, 55]])

# 정렬된 행렬의 인덱스 반환

원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스가 필요할 수도 있다.  

이때 np.argsort()를 이용하면 된다.

![100](https://user-images.githubusercontent.com/24634054/66709927-fa3b7500-eda8-11e9-9e9f-f9eac21a979e.JPG)



In [2]:
array = np.array([3, 1, 9, 5])
array_sort = np.sort(array)
array_index = np.argsort(array)
print(array_sort)
print(array_index)

[1 3 5 9]
[1 0 3 2]


이렇게 인덱스를 구할 수 있다.

# 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

**행렬 내적(행렬 곱)**

행렬 내적은 행렬 곱이며, 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산이 가능하다.

In [44]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_array = np.dot(A, B)
dot_array

array([[ 58,  64],
       [139, 154]])

**전치 행렬**

원 행렬에서 행, 열 위치를 바꾼 행렬을 전치 행렬이라고 한다. np.transpost를 이용해서 구할 수 있다.


In [45]:
A = np.transpose(A)
A

array([[1, 4],
       [2, 5],
       [3, 6]])